### ISSUE TITLE
fix permissions for lollipop

### ISSUE THREAD

**Issue by aperomsik** [openintents/convertcsv#4]
Tried to install the current OI Convert CSV in a Lollipop emulator, but it failed. Seems the same kind of issue that was fixed for OI Shopping List needs to be handled for OI Convert CSV. 

(I've switched to a KitKat emulator for now.)

**Comment by aperomsik** [comment]
I haven't tested yet, but d7ae017440650f2fb3c1777214782fad712264d2 should fix this.

**Comment by friedger** [comment]
Version 1.4.0 has been released
